### ISSUE TITLE
Composer.py

### ISSUE THREAD

**Issue by qefqefkjewn** [hvnsweeting/XuppyMail#3]
how can i use it like an ordinary mail client?
i find you use the pop protocol.
but now,most mail client use imap/smtp protocol

**Comment by Erhii** [comment]
i don't know how to use the code in lib dir.
i think it is useless...

**Comment by hvnsweeting** [comment]
> how can i use it like an ordinary mail client?
i find you use the pop protocol.
but now,most mail client use imap/smtp protocol

hi, I should have wrote in README file that this repo is just for nostalgia purpose. Though it can somehow sending email / and receive (if I remember correctly) but it is written for learning purpose in the first place. Since back then, I don't know anything about email and the code is very bad written.
Thank you for your interest, and feel free to fork/improve it as you will.
